
= BannedDependencies

This rule checks the dependencies and fails if any of the matching excludes are found.

== Trigger Phases
* AFTER_PROJECT
* AFTER_PROJECTS

== Configuration
[source,groovy]
[subs="+macros"]
----
enforce {
    rule(enforcer.rules.BannedDependencies) { r ->
        r.enabled
        r.configurations
        r.excludes
        r.includes
        r.exclude()
        r.include()
    }
}
----

== Properties

[%header, cols="<,<,<,^,<4"]
|===
| Name
| Type
| Default
| Required
| Description

| message
| Property<String>
|
| {icon_req_n}
| An optional message to the user if the rule fails.

| configurations
| ListProperty<String>
| `[]`
| {icon_req_n}
| Only verify dependencies within these configurations. Unresolvable configurations will be ignored. This rule applies +
  to all resolvable configurations if this property is left empty.

| excludes
| ListProperty<String>
| `[]`
| {icon_req_y}
| A list of artifacts to ban. The format is `groupId[:artifactId][:version][:classifier]` where `artifactId`, `version`, +
  and `classifier` are optional. Wildcards may be used to replace an entire or just parts of a section.

| includes
| ListProperty<String>
| `[]`
| {icon_req_n}
| A list of artifacts to include. These are exceptions to the excludes. It is meant to allow wide exclusion rules with +
  wildcards and fine tune using includes. If nothing has been excluded, then the includes have no effect. In other words, +
  includes only subtract from artifacts that matched an exclude rule. +
  For example, to ban all xerces except xerces-api you would exclude "xerces" (groupId) and include "xerces:xerces-api"

|===

Artifact pattern examples:

* org.apache.maven
* org.apache.maven:badArtifact
* org.apache.maven:artifact:badVersion
* org.apache.maven:*:1.2 (exclude version 1.2 and above, equivalent to [1.2,) )
* org.apache.maven:*:[1.2] (explicit exclude of version 1.2)
* org.apache.maven:*:*:test
* org.apache.+*+:maven-+*+:*

== Methods

*exclude(String str)* +
Add a dependency pattern to be excluded.

*include(String str)* +
Add a dependency pattern to be included.

== Example

[source,groovy]
[subs="+macros"]
----
enforce {
    rule(enforcer.rules.BannedDependencies) { r ->
        // search only on compile and runtime classpaths
        r.configurations.addAll(['compileClasspath', 'runtimeClasspath'])
        // ignore all classes under the following package
        r.exclude('org.apache.maven')
        r.exclude('org.apache.maven:badArtifact')
        r.exclude('*:badArtifact')
        // only 1.0 of badArtifact is allowed
        r.include('org.apache.maven:badArtifact:1.0')
    }
}
----

