
= RequireFilesSize

This rule checks that the specified list of files exist and are within the specified size range.

== Allowed Phases
* BEFORE_BUILD
* BEFORE_PROJECTS
* BEFORE_PROJECT
* AFTER_PROJECT
* AFTER_PROJECTS
* AFTER_BUILD

== Default Phases
* BEFORE_BUILD

== Configuration
[source,groovy]
[subs="+macros"]
----
enforce {
    rule(enforcer.rules.RequireFilesSize) { r ->
        r.enabled
        r.enforcerLevel
        r.message
        r.phases
        r.files
        r.includePatterns
        r.excludePatterns
        r.maxsize
        r.minsize
        r.allowNulls
        r.file()
        r.include()
        r.exclude()
    }
}
----

== Properties

[%header, cols="<,<,<,^,<4"]
|===
| Name
| Type
| Default
| Required
| Description

| allowNulls
| Property<Boolean>
| `false`
| {icon_req_n}
| If null files should be allowed. If allowed, they will be treated as if they do exist.

| files
| Property<String>
|
| {icon_req_c}
| A list of files to be checked.

| includePatterns
| ListProperty<String>
| `[ ]`
| {icon_req_c}
| List of filename patterns to include.

| excludePatterns
| ListProperty<String>
| `[ ]`
| {icon_req_c}
| List of filename patterns to exclude.

| maxsize
| Property<Long>
| `10_000L`
| {icon_req_c}
| Maximum size in bytes for this file.

| minsize
| Property<Long>
| `0L`
| {icon_req_c}
| Minimum size in bytes for this file.

|===

== Methods

*file(String str)* +
*file(File file)* +
Adds a file to the list of files to be checked. Path may be relative or absolute.

*include(String str)* +
Adds a patterns to the list of inclusion patterns to be checked. Path may be relative or absolute.

*exclude(String str)* +
Adds a patterns to the list of exclusion patterns to be checked. Path may be relative or absolute.
