
= RequireSystemProperty

This rule checks that a specified System property is set.

== Allowed Phases
* BEFORE_PROJECTS
* BEFORE_PROJECT
* AFTER_PROJECT
* AFTER_PROJECTS

== Default Phases
* BEFORE_PROJECTS
* BEFORE_PROJECT
* AFTER_PROJECT
* AFTER_PROJECTS

== Configuration
[source,groovy]
[subs="+macros"]
----
enforce {
    rule(enforcer.rules.RequireSystemProperty) { r ->
        r.enabled
        r.enforcerLevel
        r.message
        r.phases
        r.property
        r.regex
        r.regexMessage
        r.displayValue
        r.after
    }
}
----

== Properties

[%header, cols="<,<,<,^,<4"]
|===
| Name
| Type
| Default
| Required
| Description

| property
| Property<String>
|
| {icon_req_y}
| The name of the System property to be checked for.

| regex
| Property<String>
|
| {icon_req_n}
| A regular expression used to check the value of the property. +
  The regex is applied to the entire value of the property (i.e. using the regex "match" method), and not just a substring +
  of the property's value.

| regexMessage
| Property<String>
|
| {icon_req_n}
| An optional message to the user if the regex check fails.

| displayValue
| Property<Boolean>
| `true`
| {icon_req_n}
| Displays the value to the user if the regex check fails.

| after
| Property<Boolean>
| `false`
| {icon_req_n}
| Whether to check during the `BEFORE_*` or `AFTER_*` phases.

|===

== Example

[source,groovy]
[subs="+macros"]
----
enforce {
    rule(enforcer.rules.RequireSystemProperty) { r ->
        r.property = 'somePropertyName'
        r.regex = '[A-Za-z0-9]{16}'
        r.displayValue = false
    }
}
----

